#ifndef LIB_COMMON_PDM_ERRNO_H_
#define LIB_COMMON_PDM_ERRNO_H_

#define LIB_PDM_ERROR_NONE  0
#define LIB_PDM_ERROR_NO_INIT  -1
#define LIB_PDM_ERROR_FUNCTION_TYPE  -2
#define LIB_PDM_ERROR_INITIALIZED  -3
#define LIB_PDM_ERROR_WRONG_PARAM  -4
#define LIB_PDM_ERROR_NO_INPUT  -5

#endif  // LIB_COMMON_PDM_ERRNO_H_